# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    context: luggage66.com
    docker:
    - image: circleci/golang:1.12.6
      auth:
        username: _json_key  # default username when using a JSON key file to authenticate
        password: $GCLOUD_SERVICE_KEY
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false # :(
      - run:
          name: Docker Build
          command: make docker

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  Build:
    jobs:
    - build
